from sqlalchemy import (
    Column, String, Integer, Float, Boolean, CheckConstraint, ForeignKey, Index, Text
)
from sqlalchemy.orm import relationship
from storage.db import Base


class FlowORM(Base):
    """Stores metadata for windowed unidirectional traffic flows."""
    __tablename__ = "flows"

    flow_id = Column(String, primary_key=True)
    correlation_id = Column(String, nullable=False, index=True)
    src_ip = Column(String, nullable=False, index=True)
    dst_ip = Column(String, nullable=False)
    src_port = Column(Integer, nullable=False)
    dst_port = Column(Integer, nullable=False)
    protocol = Column(String, nullable=False)
    packet_count = Column(Integer, nullable=False, default=1)
    byte_count = Column(Integer, nullable=False, default=0)
    start_ts = Column(Float, nullable=False, index=True)
    end_ts = Column(Float, nullable=False, index=True)
    source = Column(
        String,
        CheckConstraint("source IN ('live', 'pcap', 'simulator_normal', 'simulator_attack', 'telemetry_api')"),
        nullable=False
    )

    # Relationships
    features = relationship("FeatureORM", back_populates="flow", uselist=False, cascade="all, delete-orphan")
    model_results = relationship("ModelResultORM", back_populates="flow", cascade="all, delete-orphan")
    alerts = relationship("AlertORM", back_populates="flow", cascade="all, delete-orphan")


class FeatureORM(Base):
    """Stores the 13-feature vector fed to ML models per flow."""
    __tablename__ = "features"

    flow_id = Column(String, ForeignKey("flows.flow_id", ondelete="CASCADE"), primary_key=True)
    total_packets = Column(Float, nullable=False)
    total_bytes = Column(Float, nullable=False)
    avg_packet_size = Column(Float, nullable=False)
    flow_duration = Column(Float, nullable=False)
    mean_iat = Column(Float, nullable=False)
    iat_variance = Column(Float, nullable=False)
    unique_dst_ip_count = Column(Float, nullable=False)
    unique_dst_port_count = Column(Float, nullable=False)
    tcp_ratio = Column(Float, nullable=False, default=0.0)
    udp_ratio = Column(Float, nullable=False, default=0.0)
    icmp_ratio = Column(Float, nullable=False, default=0.0)
    small_large_pkt_ratio = Column(Float, nullable=False)
    byte_entropy = Column(Float, nullable=False)

    flow = relationship("FlowORM", back_populates="features")


class ModelResultORM(Base):
    """Stores raw supervised and unsupervised model outputs per flow."""
    __tablename__ = "model_results"

    result_id = Column(String, primary_key=True)
    flow_id = Column(String, ForeignKey("flows.flow_id", ondelete="CASCADE"), nullable=False, index=True)
    rf_class = Column(String, nullable=False)
    rf_probability = Column(Float, nullable=False)
    if_anomaly_score = Column(Float, nullable=False)
    model_version = Column(String, nullable=False)
    inference_ts = Column(Float, nullable=False)

    flow = relationship("FlowORM", back_populates="model_results")


class AlertORM(Base):
    """Stores human-facing security alerts generated by the Risk Engine."""
    __tablename__ = "alerts"

    alert_id = Column(String, primary_key=True)
    correlation_id = Column(String, nullable=False, index=True)
    flow_id = Column(String, ForeignKey("flows.flow_id", ondelete="CASCADE"), nullable=False)
    risk_score = Column(
        Integer,
        CheckConstraint("risk_score BETWEEN 0 AND 100"),
        nullable=False
    )
    severity = Column(
        String,
        CheckConstraint("severity IN ('Informational', 'Low', 'Medium', 'High', 'Critical')"),
        nullable=False,
        index=True
    )
    confidence = Column(
        Float,
        CheckConstraint("confidence BETWEEN 0.0 AND 1.0"),
        nullable=False
    )
    threat_category = Column(String, nullable=False)
    explanation = Column(Text, nullable=False)
    top_features = Column(Text, nullable=False)  # JSON string array
    geolocation = Column(Text, nullable=False)   # JSON string object
    status = Column(
        String,
        CheckConstraint("status IN ('new', 'acknowledged', 'false_positive')"),
        nullable=False,
        default="new",
        index=True
    )
    notes = Column(Text, default="")
    created_ts = Column(Float, nullable=False, index=True)

    flow = relationship("FlowORM", back_populates="alerts")


class ThreatIntelIPORM(Base):
    """Stores offline historical attacking IP reputation data."""
    __tablename__ = "threat_intel_ips"

    ip = Column(String, primary_key=True)
    threat_score = Column(
        Integer,
        CheckConstraint("threat_score BETWEEN 0 AND 100"),
        nullable=False
    )
    category = Column(String, nullable=False, index=True)
    source_feed = Column(String, nullable=False)
    country_code = Column(String, default="XX")
    last_seen = Column(Float, nullable=False)


class ThreatIntelCIDRORM(Base):
    """Stores offline CIDR subnet blacklists."""
    __tablename__ = "threat_intel_cidrs"

    cidr_id = Column(String, primary_key=True)
    cidr_block = Column(String, nullable=False, unique=True, index=True)
    threat_score = Column(
        Integer,
        CheckConstraint("threat_score BETWEEN 0 AND 100"),
        nullable=False
    )
    category = Column(String, nullable=False)
    source_feed = Column(String, nullable=False)
    created_ts = Column(Float, nullable=False)


class UserORM(Base):
    """Stores user accounts for toggleable authentication and audit trail."""
    __tablename__ = "users"

    user_id = Column(String, primary_key=True)
    username = Column(String, nullable=False, unique=True, index=True)
    email = Column(String, nullable=False, unique=True, index=True)
    hashed_password = Column(String, nullable=False)
    role = Column(
        String,
        CheckConstraint("role IN ('analyst', 'admin')"),
        nullable=False,
        default="analyst"
    )
    is_active = Column(Boolean, nullable=False, default=True)
    created_ts = Column(Float, nullable=False)

